categories:

    - channel:
        board: 'Engineering: Channel'
        list: Inbox
        channel: dev-team-channel
        terms:
            - channel

    - discovery:
        board: 'Engineering: Search'
        list: Inbox
        channel: dev-team-discovery
        terms:
            - discovery
            - index
            - search

    - queue:
        board: 'Engineering: Team Q'
        list: Inbox
        channel: dev-team-q
        terms:
            - coding_exercises
            - quiz

    - u:
        board: 'Engineering: Team U'
        list: Inbox
        channel: dev-team-u
        terms:
            - clp
    - g:
        board: 'Engineering: Team G'
        list: Inbox
        channel: dev-team-g
        terms:
            - AppleInAppPurchaseConnectionException
            - facebookads
            - googleapis
            - preview video

    - tea:
        board: 'Engineering: Team Tea'
        list: Inbox
        channel: dev-team-t
        terms:
            - course_management
            - terms
            - ban_helper

    - learning:
        board: 'Team L - Inbox'
        channel: dev-team-l
        list: 
        terms:
            - videojs
            - user_manage

    - payments:
        board: 'Engineering: Team A - Payment'
        list: 
        channel: dev-team-payments
        terms:
            - paypal
            - payment
            - stripe
            - fraud
            - adyen

    - stream:
        board: 'Engineering: Stream Team'
        list: Inbox
        channel: dev-stream-team
        terms:
             - asset
             - image
             - pymysql
             - MySQL
             - caption
             - closed-caption-ms

    - bedrock:
        board: 'Engineering: Team Bedrock'
        list: Inbox
        channel: dev-team-b
        terms:
             - zdesk
             - ZenDesk
             - responsys

    - ufb:
        board: 'Engineering: UFB'
        channel: team-ufb-eng
        list: Inbox
        terms:
             - organization
             - sso
